services:
  #Create a service named "mysql_db" from the image "mariadb:latest"
  mysql_db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products-db #Database name
      MYSQL_USER: admin #Database user
      MYSQL_PASSWORD: admin #Database password
    volumes:
      - mysql_data:/var/lib/mysql
    restart:
        always
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 1m30s
        timeout: 10s
        retries: 3
  #-----------------------------------------------------------------
  #Create a service named "phpmyadmin_db" from the image "phpmyadmin"
  phpmyadmin_db:
    image: phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: admin
    container_name: phpmyadmin
    depends_on:
      - mysql_db
    restart:
        always
  #-----------------------------------------------------------------
  #Create a service named "products_ms" from the image "products_ms"
  products_ms:
    build: ./Products_MS_Secured
    ports:
      - "8083:8083"
    container_name: products_ms
    depends_on:
      - mysql_db
      - keycloak_service
    environment:
      - DB_VARIABLE=jdbc:mysql://mysql_db:3306/products
      - ISSUER_URI=http://localhost:8080/realms/auth_apps
      - JWT_URI=http://keycloak_service:8080/realms/auth_apps/protocol/openid-connect/certs

  #-----------------------------------------------------------------
  #Create a service named "postgres_db" from the image "postgres
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    restart:
        always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
  #-----------------------------------------------------------------
  #Create a service named "pgadmin_db" from the image "pgadmin4"
  #This One is like phpmyadmin but for postgres
  pgadmin_db:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_USER: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: abdeljalil@gmail.com

    container_name: pgadmin_db
    restart:
      always
  #-----------------------------------------------------------------
  keycloak_service:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    container_name: keycloak_service
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    depends_on:
      - postgres_db
    command:
      - start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]

  #-----------------------------------------------------------------
  # Create a service named "thymeleaf_app"
  #Create a service named "phpmyadmin_db" from the image "phpmyadmin"
  mysql_db_thymeleaf:
    image: mariadb:latest
    ports:
      - "3307:3306"
    container_name: mysql_db_thymeleaf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: costumers_db #Database name
      MYSQL_USER: admin #Database user
      MYSQL_PASSWORD: admin #Database password
    volumes:
      - mysql_data:/var/lib/mysqlthymeleaf
    restart:
      always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
  phpmyadmin_db_thymeleaf:
    image: phpmyadmin
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql_db_thymeleaf
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: admin
    container_name: phpmyadmin_thymeleaf
    depends_on:
      - mysql_db_thymeleaf
    restart:
      always

  thymeleaf_app:
    build: ./Thymleaf_App_secured
    ports:
      - "8081:8081"
    container_name: thymeleaf_app
    depends_on:
      - mysql_db_thymeleaf
      - keycloak_service

    environment:
      - DB_URL=jdbc:mysql://mysql_db_thymeleaf:3306/costumers_db
      - PRODUCT_SERVICE_URL=http://products_ms:8083
      - REDIRECT_URI=http://localhost:8081/login/oauth2/code/ebank_app_ms #goal of this is to redirect to this url after login
      - KEYCLOAK_AUTH=http://localhost:8080/realms/auth_apps/protocol/openid-connect/auth
      - KEYCLOAK_AUTH_TOKEN=http://localhost:8080/realms/auth_apps/protocol/openid-connect/token
      - JWT_JWK_SET_URI=http://keycloak_service:8080/realms/auth_apps/protocol/openid-connect/certs
      - ISSUER_URI=http://localhost:8080/realms/auth_apps
      - CLIENT_NAME=ebank_app_ms
    restart: always
  #-----------------------------------------------------------------
  #Create Angular App
  angular_app:
      build: ./angular_app_front/front_app
      ports:
        - "8085:80"
      expose:
        - "8085"
      container_name: angular_app
      restart: always
#Declare a volumes
volumes:
    mysql_data:
    postgres_data:
    mysqlthymeleaf: