services:
  #Create a service named "mysql_db" from the image "mariadb:latest"
  mysql_db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products-db #Database name
      MYSQL_USER: admin #Database user
      MYSQL_PASSWORD: admin #Database password
    volumes:
      - mysql_data:/var/lib/mysql
    restart:
        always
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 1m30s
        timeout: 10s
        retries: 3
  #-----------------------------------------------------------------
  #Create a service named "phpmyadmin_db" from the image "phpmyadmin"
  phpmyadmin_db:
    image: phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: admin
    container_name: phpmyadmin
    depends_on:
      - mysql_db
    restart:
        always
  #-----------------------------------------------------------------
  #Create a service named "products_ms" from the image "products_ms"
  products_ms:
    build: ./Products_MS_Secured
    ports:
      - "8083:8083"
    container_name: products_ms
    depends_on:
      - mysql_db
      - keycloak_service
    environment:
      - DB_VARIABLE=jdbc:mysql://mysql_db:3306/products
      - ISSUER_URI=http://keycloak_service:8080/realms/auth_apps
      - JWT_URI=http://keycloak_service:8080/auth/realms/auth_apps/protocol/openid-connect/certs

  #-----------------------------------------------------------------
  #Create a service named "postgres_db" from the image "postgres
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    restart:
        always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
  #-----------------------------------------------------------------
  #Create a service named "pgadmin_db" from the image "pgadmin4"
  #This One is like phpmyadmin but for postgres
  pgadmin_db:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_USER: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: abdeljalil@gmail.com

    container_name: pgadmin_db
    restart:
      always
  #-----------------------------------------------------------------
  keycloak_service:
    image: keycloak/keycloak:latest
    ports:
      - "8080:8080"
    container_name: keycloak_service
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    depends_on:
      - postgres_db
    command:
      - start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
#Declare a volumes
volumes:
    mysql_data:
    postgres_data: